// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCU1vBzvfczxLFMciM_-_Trp_HcLSVzArA',
    appId: '1:361819871944:web:85ec36b0097702b5e5a3fd',
    messagingSenderId: '361819871944',
    projectId: 'team2project-4b7f5',
    authDomain: 'team2project-4b7f5.firebaseapp.com',
    storageBucket: 'team2project-4b7f5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvKp_1tmshSQBEH20gyhxPJOrjO0eJEPc',
    appId: '1:361819871944:android:fc8922a58f3c91a7e5a3fd',
    messagingSenderId: '361819871944',
    projectId: 'team2project-4b7f5',
    storageBucket: 'team2project-4b7f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7k_hNR83Sp9eNgESoTq5IWPEoF9c09Ms',
    appId: '1:361819871944:ios:68db9a2d70cbb0cae5a3fd',
    messagingSenderId: '361819871944',
    projectId: 'team2project-4b7f5',
    storageBucket: 'team2project-4b7f5.firebasestorage.app',
    androidClientId: '361819871944-qhinbjhr9b4vlb5p63ij2di7de68qpe2.apps.googleusercontent.com',
    iosClientId: '361819871944-25m3baji3bgcg19qublb457stfl87igi.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7k_hNR83Sp9eNgESoTq5IWPEoF9c09Ms',
    appId: '1:361819871944:ios:68db9a2d70cbb0cae5a3fd',
    messagingSenderId: '361819871944',
    projectId: 'team2project-4b7f5',
    storageBucket: 'team2project-4b7f5.firebasestorage.app',
    androidClientId: '361819871944-qhinbjhr9b4vlb5p63ij2di7de68qpe2.apps.googleusercontent.com',
    iosClientId: '361819871944-25m3baji3bgcg19qublb457stfl87igi.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCU1vBzvfczxLFMciM_-_Trp_HcLSVzArA',
    appId: '1:361819871944:web:a43fc9519a57394ee5a3fd',
    messagingSenderId: '361819871944',
    projectId: 'team2project-4b7f5',
    authDomain: 'team2project-4b7f5.firebaseapp.com',
    storageBucket: 'team2project-4b7f5.firebasestorage.app',
  );

}