// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9srgXMjzq_0UX3PYPBWW2Gxshkcb3e2Y',
    appId: '1:1054498550686:web:2a20c447937ac6c1a71c8f',
    messagingSenderId: '1054498550686',
    projectId: 'flutter1-8b0ca',
    authDomain: 'flutter1-8b0ca.firebaseapp.com',
    storageBucket: 'flutter1-8b0ca.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzVDVtbXcdS3QTUwSLWq6Bi12NDnuog7I',
    appId: '1:1054498550686:android:25883235643fcbc9a71c8f',
    messagingSenderId: '1054498550686',
    projectId: 'flutter1-8b0ca',
    storageBucket: 'flutter1-8b0ca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyD2eqbAtJToNoxgG7k_dGyW1CU3jhRpk',
    appId: '1:1054498550686:ios:721e0d3e49ae2231a71c8f',
    messagingSenderId: '1054498550686',
    projectId: 'flutter1-8b0ca',
    storageBucket: 'flutter1-8b0ca.firebasestorage.app',
    androidClientId: '1054498550686-8u85h3qblvmrvhd5b8ompn67718lr9ia.apps.googleusercontent.com',
    iosClientId: '1054498550686-o0n921r34atn4ugiop92h7va2ldnhtge.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyD2eqbAtJToNoxgG7k_dGyW1CU3jhRpk',
    appId: '1:1054498550686:ios:721e0d3e49ae2231a71c8f',
    messagingSenderId: '1054498550686',
    projectId: 'flutter1-8b0ca',
    storageBucket: 'flutter1-8b0ca.firebasestorage.app',
    androidClientId: '1054498550686-8u85h3qblvmrvhd5b8ompn67718lr9ia.apps.googleusercontent.com',
    iosClientId: '1054498550686-o0n921r34atn4ugiop92h7va2ldnhtge.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9srgXMjzq_0UX3PYPBWW2Gxshkcb3e2Y',
    appId: '1:1054498550686:web:c166750157c948d5a71c8f',
    messagingSenderId: '1054498550686',
    projectId: 'flutter1-8b0ca',
    authDomain: 'flutter1-8b0ca.firebaseapp.com',
    storageBucket: 'flutter1-8b0ca.firebasestorage.app',
  );
}
