// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart'; // dotenv import 추가

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // 런타임에 값을 읽어야 하므로 const를 삭제하고 static으로 변경했습니다.
  static FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_WEB_API_KEY']!,
    appId: dotenv.env['FIREBASE_WEB_APP_ID']!,
    messagingSenderId: dotenv.env['FIREBASE_MESSAGING_SENDER_ID']!,
    projectId: dotenv.env['FIREBASE_PROJECT_ID']!,
    authDomain: 'team2project-4b7f5.firebaseapp.com',
    storageBucket: dotenv.env['FIREBASE_STORAGE_BUCKET']!,
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_ANDROID_API_KEY']!,
    appId: dotenv.env['FIREBASE_ANDROID_APP_ID']!,
    messagingSenderId: dotenv.env['FIREBASE_MESSAGING_SENDER_ID']!,
    projectId: dotenv.env['FIREBASE_PROJECT_ID']!,
    storageBucket: dotenv.env['FIREBASE_STORAGE_BUCKET']!,
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_IOS_API_KEY']!,
    appId: dotenv.env['FIREBASE_IOS_APP_ID']!,
    messagingSenderId: dotenv.env['FIREBASE_MESSAGING_SENDER_ID']!,
    projectId: dotenv.env['FIREBASE_PROJECT_ID']!,
    storageBucket: dotenv.env['FIREBASE_STORAGE_BUCKET']!,
    androidClientId: '361819871944-qhinbjhr9b4vlb5p63ij2di7de68qpe2.apps.googleusercontent.com',
    iosClientId: '361819871944-25m3baji3bgcg19qublb457stfl87igi.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7k_hNR83Sp9eNgESoTq5IWPEoF9c09Ms',
    appId: '1:361819871944:ios:68db9a2d70cbb0cae5a3fd',
    messagingSenderId: '361819871944',
    projectId: 'team2project-4b7f5',
    storageBucket: 'team2project-4b7f5.firebasestorage.app',
    androidClientId: '361819871944-qhinbjhr9b4vlb5p63ij2di7de68qpe2.apps.googleusercontent.com',
    iosClientId: '361819871944-25m3baji3bgcg19qublb457stfl87igi.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCU1vBzvfczxLFMciM_-_Trp_HcLSVzArA',
    appId: '1:361819871944:web:a43fc9519a57394ee5a3fd',
    messagingSenderId: '361819871944',
    projectId: 'team2project-4b7f5',
    authDomain: 'team2project-4b7f5.firebaseapp.com',
    storageBucket: 'team2project-4b7f5.firebasestorage.app',
  );

}